nav/navbar colors, highlights, layouts
KarelFalusi/ghc pull request #4
Opened 2022-09-15 14:39 UTC by KarelFalusi

2022-09-16 07:19 UTC, benabraham requested changes
Tam kde píšu že to není dobře, tak prosím oprav.
Plus mrkni na vertikální mezery v hlavičce
![image](https://user-images.githubusercontent.com/334494/190579447-b920fae0-d812-4350-84f1-83c181ea0d9b.png)

2022-09-16 07:19 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +    $nav-link-color: $cyan; $nav-link-color: $nav-link-color !global; // var(--#{$prefix}link-color)
👍

2022-09-16 07:19 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +    $navbar-nav-link-padding-x: 1rem; $navbar-nav-link-padding-x: $navbar-nav-link-padding-x !global; // .5rem
![image](https://user-images.githubusercontent.com/334494/190575162-bc75404f-b7cc-4b1a-a476-bf4928883c82.png)
nahoře bys měl mít zase menší gap o to

2022-09-16 07:19 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +    $navbar-nav-link-padding-x: 1rem; $navbar-nav-link-padding-x: $navbar-nav-link-padding-x !global; // .5rem
viz návrh 
![image](https://user-images.githubusercontent.com/334494/190575241-f5f22554-a1fa-4dcb-a99d-512da36ffd3f.png)

2022-09-16 07:19 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +    $navbar-nav-link-padding-x: 1rem; $navbar-nav-link-padding-x: $navbar-nav-link-padding-x !global; // .5rem
a na mobilu se na to podívej
![menu-320](https://user-images.githubusercontent.com/334494/190576072-9a7e59a9-589a-458e-bf81-009dafb743aa.png)

2022-09-16 07:19 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +    $navbar-light-active-color: $gray-900; $navbar-light-active-color: $navbar-light-active-color !global; // rgba($black, .9)
nemusíš měnit, ale já bych dal hover asi černej

2022-09-16 07:19 UTC, benabraham commented on src/templates/_base.njk
> +                <div class="container px-0">
defenziněji: text dole může být až do kraje, pokud by byl delší nebo větším písmem

2022-09-16 07:19 UTC, benabraham commented on src/templates/_base.njk
> +                            <a class="nav-link {% block navOurStory2 %}{% endblock %}" href="/our-story">Our Story</a>
asi bych pojmenoval ty bloky spíš podle toho, že jsou dole něco jako 
`navFooterHome` apod.

2022-09-16 07:19 UTC, benabraham commented on src/templates/coffee.njk
>  {% block content %}
Mám tendenci mezi bloky dávat mezery (prázdné řádky) pro přehlednost, ale ok, ničemu to nevadí.

2022-09-16 07:19 UTC, benabraham commented on src/templates/index.njk
> +                <a class="text-decoration-none text-dark" href="tel:+14153214567">+1 415-321-4567</a>
Je to sice podle návrhu, ale takhle uživatel nebude vědět, že to je odkaz.
V návrhu to vypadá, že nikdo nepočítal s tím, že to odkaz bude.
Takže to nech jako standardní odkaz.

2022-09-17 15:26 UTC, KarelFalusi commented
[more accurate nav, **menu** - má tam být **home** page layout](https://github.com/KarelFalusi/ghc/pull/4/commits/52ffaceaa5612857ee049e07d3649d68acab6c8b)

2022-09-19 10:56 UTC, benabraham requested changes
mrkni na komenty a oprav

2022-09-19 10:56 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +        6: $spacer * 2,
2remy by asi měl být spíš spacer 5

2022-09-19 10:56 UTC, benabraham commented on src/scss/_customized-bootstrap-variables.scss
> +    $navbar-brand-margin-end: 0rem; $navbar-brand-margin-end: $navbar-brand-margin-end !global; // 1rem
```suggestion
    $navbar-brand-margin-end: 0; $navbar-brand-margin-end: $navbar-brand-margin-end !global; // 1rem
```

2022-09-19 10:56 UTC, benabraham commented on src/templates/_base.njk
> +            <nav class="navbar navbar-light navbar-expand bg-light mb-4 pt-2 pb-2">
```suggestion
            <nav class="navbar navbar-light navbar-expand bg-light mb-4 py-2">
```
kratší zápis, když jsou stejné v x nebo y

2022-09-19 10:56 UTC, benabraham commented on src/templates/_base.njk
> +                        <img src="/svg/logo.svg" alt="Generic Hipster Coffee" width="180" height="180"/>
pozor na velikost na širším viewportu

2022-09-19 10:56 UTC, benabraham commented on src/templates/_base.njk
> +                    <ul class="navbar-nav gap-lg-3">
![image](https://user-images.githubusercontent.com/334494/191000555-41b0aaa4-bb41-4dba-b09f-2b4e5037aa09.png)
asi by to sneslo dříve větší mezery

2022-09-19 10:56 UTC, benabraham commented on src/templates/_base.njk
> +                    <ul class="navbar-nav gap-lg-3">
![image](https://user-images.githubusercontent.com/334494/191000756-31c749aa-3131-4a91-a5f5-a69755065ad7.png)
vlastne i tady

2022-09-19 10:56 UTC, benabraham commented on src/templates/_base.njk
> +                    <ul class="nav justify-content-center align-items-flex-start mb-2">
Lze dosáhnout nezalomení + padding pro footer (resp. jeho container)
```suggestion
                <div class="container">
                    <ul class="nav justify-content-center align-items-flex-start mb-2 mx-n2">
```

2022-09-19 10:56 UTC, benabraham commented on src/templates/index.njk
> +                <a class="text-decoration-none" href="tel:+14153214567">+1 415-321-4567</a>
```suggestion
                <a href="tel:+14153214567">+1 415-321-4567</a>
```
nechat podtržení

2022-09-19 12:12 UTC, benabraham requested changes

2022-09-19 12:12 UTC, benabraham commented on src/templates/_base.njk
> +            <nav class="navbar navbar-light navbar-expand bg-light mb-4 py2">
```suggestion
            <nav class="navbar navbar-light navbar-expand bg-light mb-4 py-2">
```

2022-09-19 12:14 UTC, benabraham approved these changes

2022-09-19 12:18 UTC, merged